### ISSUE TITLE
Project does not build - loads of missing dependencies 

### ISSUE THREAD

**Issue by johnmchale** [onurkarakus/cqrsMediatorPattern#2]
dotnet restore 
does nothing either 

<img width="649" alt="image" src="https://user-images.githubusercontent.com/38525955/221426752-b652bd02-1a09-42e7-bec9-c51a159f989a.png">

**Comment by onurkarakus** [comment]
Hi, cloned the codes again to be sure. When i start the command dotnet restore in my local machine. There is nothing wrong and all the packets restored. Is there another warning or error when restoring your packages? I take a screen shot about restore operations on my machine. 


![restore](https://user-images.githubusercontent.com/7154232/221428506-04222317-2782-46d8-ad5e-c32a46d7b41d.PNG)

**Comment by johnmchale** [comment]
I'm.using Visual Studio 2022 ,latest edition, what version are you using?
Thanks
John

**Comment by onurkarakus** [comment]
Hi, I am using 2022 too in my project. 

![Version](https://user-images.githubusercontent.com/7154232/221437578-3ae5a564-2f2d-4e77-8e4b-86bec7742632.PNG)

Could it be another error while installing packages? Getting an error while installing packages via Nuget?

**Comment by johnmchale** [comment]
sorry, but I'm not sure what else to do. Yiu can see what I get in the
screenshot

**Comment by johnmchale** [comment]
I just opened up a couple of other projects, alk broken with dependency
issues, so it's something wrong with my Visual studio. I will delete the
issue, so sorry for the inconvenience

**Comment by onurkarakus** [comment]
Does not matter. I couldn't help with the solution. I hope a solution is found.

**Comment by johnmchale** [comment]
Thanks Onur, as I said, there is nothing wrong with your repo.

There was something wrong with my Visual Studio 2022 - The latest install
messed things up.
I did a repair (i.e. like a fresh install) and everything is working fine
now.

Thanks for writing the article and the repo 👍
